export enum RoleStatus {
  CREATED = 'CREATED',
  AUTHORIZED = 'AUTHORIZED',
  RESTRICTED = 'RESTRICTED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  DELETED = 'DELETED'
}

export enum RoleType {
  OWNER = 'OWNER',
  PARTNER = 'PARTNER',
  BUYER = 'BUYER',
  BROKER = 'BROKER',
  MASTERBROKER = 'MASTERBROKER',
  NOTARY = 'NOTARY',
  ADMIN = 'ADMIN'
}

export enum UserStatus {
  CREATED = 'CREATED',
  AUTHORIZED = 'AUTHORIZED',
  UNAUTHORIZED = 'UNAUTHORIZED'
}
